#!/bin/bash

# Since we are sourcing build file, should be careful here not to create any function as they may get shadowed by us

BUDFILE="Budfile"
if [ -r "$BUDFILE" ]; then
    source "$BUDFILE"
else
    echo "No $BUDFILE found" 2>/dev/null
    exit 1
fi

if [ "$#" -eq 0 ]; then
    echo "No argument specified, specifying one of the following build command: $(compgen -A function)" 2>/dev/null
    exit 1
elif [ "$1" = "-x" ]; then
    shift
    set -x
fi

$*
